"""Generate the fact pages under docs/generated/ from dictionary/catalog.yaml, the registries, and results.

    python -m recbench.dictionary.build              # facts + per-method results
    python -m recbench.report.build --tier smoke --out reports/smoke-latest --docs   # leaderboards

Hand-written pages in docs/ embed these files with snippets, e.g.
    --8<-- "generated/methods/ease.md"
so every number in the docs comes from code, never from copy-paste. Links inside
a fragment are written relative to the page that embeds it:
methods/*.md and capability.md -> docs/dictionary/algorithms/, datasets/*.md ->
docs/dictionary/datasets/, metrics.md -> docs/dictionary/metrics/.
The build fails if a registered method, metric, or dataset has no catalog entry.
"""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
from typing import Any

import yaml

from recbench.protocol import Task
from recbench.registry import ensure_loaded

TASK_ORDER = [t.value for t in Task]
DIRECTION = {
    "implementation": "higher = more work",
    "tuning": "higher = more work",
    "data_hunger": "higher = needs more data",
    "controllability": "higher = easier to steer",
    "explainability": "higher = clearer reasons",
}


class CatalogError(Exception):
    pass


def load_catalog(root: Path) -> dict[str, Any]:
    with (root / "dictionary" / "catalog.yaml").open() as handle:
        return yaml.safe_load(handle)


def _table(header: list[str], rows: list[list[str]]) -> str:
    lines = ["| " + " | ".join(header) + " |", "|" + "|".join("---" for _ in header) + "|"]
    lines += ["| " + " | ".join(str(c) for c in row) + " |" for row in rows]
    return "\n".join(lines) + "\n"


def _yes(flag: bool) -> str:
    return "yes" if flag else "no"


def method_facts(name: str, entry: dict[str, Any], spec: Any, ladder: dict[int, str]) -> str:
    paper = entry.get("paper")
    paper_text = f"[{paper['title']}]({paper['url']}) ({paper['venue']})" if paper else "—"
    code = f"[{entry['code']}]({entry['code']})" if entry.get("code") else "in-repo"
    rows = [
        ["Family", entry["family"]],
        ["Ladder rung", f"{entry['rung']} — {ladder[entry['rung']]}"],
        ["Paper", paper_text],
        ["Reference code", code],
        ["What recbench runs", spec.upstream],
        ["Fidelity", entry["fidelity"]],
        ["Tasks", ", ".join(t for t in TASK_ORDER if Task(t) in spec.tasks)],
        ["Uses the user's history", _yes(spec.uses_history)],
        ["Can recommend brand-new items", _yes(spec.scores_cold_items)],
        ["Needs item text/categories", _yes(spec.requires_side_features)],
        ["Needs images", _yes(spec.requires_images)],
        ["Ranked on the leaderboard", _yes(spec.ranked)],
        ["Needs PyTorch", _yes(spec.needs_torch)],
        ["Cost band", spec.cost_band],
    ]
    rubric_rows = [[dim, f"{score} / 5", DIRECTION[dim], why] for dim, (score, why) in entry["rubric"].items()]
    return (
        f"<!-- generated by recbench.dictionary.build from dictionary/catalog.yaml; do not edit -->\n\n"
        + _table(["Fact", "Value"], rows)
        + "\n**Qualitative rubric** ([how the scores are defined](../metrics/qualitative-rubric.md))\n\n"
        + _table(["Dimension", "Score", "Direction", "Why"], rubric_rows)
    )


def method_results(name: str, frames: dict[str, Any], impl_version: str = "1") -> str:
    rows, older = [], set()
    for tier, frame in frames.items():
        if frame is None or frame.empty:
            continue
        mine = frame[frame["tags.method"] == name]
        for _, r in mine.sort_values("tags.dataset").iterrows():
            def m(key: str, digits: int = 4) -> str:
                value = r.get(f"metrics.{key}")
                return "–" if value is None or value != value else f"{value:.{digits}f}"

            ci = ""
            if r.get("metrics.ndcg_at_10_ci_low") == r.get("metrics.ndcg_at_10_ci_low"):
                ci = f" [{m('ndcg_at_10_ci_low')}, {m('ndcg_at_10_ci_high')}]"
            run_version = str(r.get("tags.impl_version") if isinstance(r.get("tags.impl_version"), str) else "1")
            label = tier
            if run_version != str(impl_version):  # produced by an earlier version of this method's code
                older.add(run_version)
                label = f"{tier} †"
            rows.append([label, r["tags.dataset"], m("ndcg_at_10") + ci, m("next_ndcg_at_10"), m("coverage_at_10", 3), m("train_seconds", 1)])
    if not rows:
        return "<!-- generated -->\n\n_No finished runs yet._\n"
    text = "<!-- generated -->\n\n" + _table(["Tier", "Dataset", "NDCG@10 [95% CI]", "Next NDCG@10", "Coverage@10", "Train s"], rows)
    if older:
        text += (f"\n† Run with an earlier version of this method's code (implementation version {', '.join(sorted(older))}; "
                 f"the code is now at version {impl_version}). Running it again updates the row.\n")
    return text


def dataset_facts(name: str, entry: dict[str, Any], spec: Any, data_dir: Path) -> str:
    rows = [
        ["Domain", entry["domain"]],
        ["Source", f"[{entry['source']}]({entry['source']})"],
        ["Cite as", entry["citation"]],
        ["License", entry["license"]],
        ["Commercial use", entry["commercial_use"]],
        ["Feedback", entry["feedback"]],
        ["Side information", entry["side_info"]],
        ["Split rule", "last 7 days = test" if spec.split_rule == "last_days" else "last 10% of events (by time) = test"],
        ["Repeat policies", ", ".join(spec.repeat_policies)],
        ["Known pitfalls", entry["pitfalls"]],
    ]
    text = "<!-- generated by recbench.dictionary.build; do not edit -->\n\n" + _table(["Fact", "Value"], rows)
    stats = []
    for meta_path in sorted((data_dir / "splits" / name).glob("*/meta.json")):
        meta = json.loads(meta_path.read_text())
        if meta.get("fold"):  # validation folds are described on the quick-tier page
            continue
        stats.append([meta["tier"], f"{meta['n_users']:,}", f"{meta['n_items']:,}", f"{meta['n_pretest']:,}", f"{meta['n_test']:,}",
                      f"{meta['n_eval_warm']:,}", f"{meta['n_cold_test_users']:,}", f"{meta['repeat_share']:.1%}", meta["test_start"]])
    if stats:
        text += "\n**Splits on this machine**\n\n" + _table(
            ["Tier", "Users", "Items", "Pre-test events", "Test events", "Warm eval users", "Cold test users", "Repeat share", "Test starts (UTC)"], stats
        )
    return text


README_START = "<!-- generated:methods (python -m recbench.dictionary.build writes this block; do not edit) -->"
README_END = "<!-- /generated:methods -->"


def _ladder_order(catalog: dict[str, Any], names: Any) -> list[str]:
    """By rung, then year (oldest first), then the catalog's own order (Random before MostPopular)."""
    position = {n: i for i, n in enumerate(catalog["methods"])}
    return sorted(names, key=lambda n: (catalog["methods"][n]["rung"], catalog["methods"][n].get("year") or 0, position[n]))


def _page(name: str) -> str:
    return f"{name.replace('_', '-')}.md"


def quick_methods(root: Path) -> list[str]:
    """The methods queued in the quick-tier bake-off (configs/benchmarks/quick.yaml), in queue order."""
    path = root / "configs" / "benchmarks" / "quick.yaml"
    if not path.exists():
        return []
    return [e["name"] for e in ((yaml.safe_load(path.read_text()) or {}).get("queue") or {}).get("methods") or []]


def ladder_table(catalog: dict[str, Any], reg: Any) -> str:
    ladder, ideas = catalog["ladder"], catalog.get("ladder_ideas") or {}
    rows = []
    for rung in sorted(int(r) for r in ladder):
        names = [n for n in _ladder_order(catalog, reg.methods) if catalog["methods"][n]["rung"] == rung]
        links = [f"[{catalog['methods'][n]['title']}]({_page(n)})" for n in names]
        if rung == 7:
            links.append("[other services](managed-services.md)")
        rows.append([f"{rung} — {ladder[rung]}", str(ideas.get(rung, "")), ", ".join(links)])
    return "<!-- generated -->\n\n" + _table(["Rung", "Idea it adds", "Methods"], rows)


def glance_table(catalog: dict[str, Any], reg: Any, quick: list[str]) -> str:
    rows = []
    for n in _ladder_order(catalog, reg.methods):
        entry = catalog["methods"][n]
        where = "bake-off" if n in quick else ("managed" if reg.methods[n].spec.managed else "held back")
        rows.append([f"[{entry['title']}]({_page(n)})", str(entry["rung"]), where, entry.get("one_liner", "")])
    rows.append(["[Other managed services](managed-services.md)", "7", "docs only",
                 "Amazon Personalize, Google's commerce recommender, Azure Personalizer (retired)."])
    return ("<!-- generated -->\n\n" + _table(["Method", "Rung", "Status", "One-line idea"], rows)
            + "\n**Status:** *bake-off* = in the quick-tier bake-off, tuned with the same budget as every other method; "
              "*held back* = heavier, waiting for its turn through the same gate; *managed* = a hosted service.\n")


def readme_block(catalog: dict[str, Any], reg: Any, quick: list[str]) -> str:
    ladder = catalog["ladder"]
    lines = [README_START, "",
             f"**{len(reg.methods)} methods** on a ladder from simplest to most complex; the {len(quick)} in **bold** are in the "
             "quick-tier bake-off, the others are held back (heavier) or a managed service.", "",
             "| Rung | Methods |", "|---|---|"]
    for rung in sorted(int(r) for r in ladder):
        names = [n for n in _ladder_order(catalog, reg.methods) if catalog["methods"][n]["rung"] == rung]
        shown = [f"**{catalog['methods'][n]['title']}**" if n in quick else catalog["methods"][n]["title"] for n in names]
        lines.append(f"| {rung} {ladder[rung]} | {', '.join(shown)} |")
    return "\n".join(lines + ["", README_END])


def update_readme(root: Path, block: str) -> bool:
    """Replace the generated block of README.md; returns True when the file changed."""
    path = root / "README.md"
    if not path.exists():
        return False
    text = path.read_text()
    if README_START not in text or README_END not in text:
        return False
    head, rest = text.split(README_START, 1)
    _, tail = rest.split(README_END, 1)
    new = head + block + tail
    if new != text:
        path.write_text(new)
    return new != text


def build(root: Path | None = None, data_dir: Path | None = None, with_results: bool = True) -> Path:
    root = (root or Path.cwd()).resolve()
    data_dir = data_dir or Path(os.environ.get("DATA_DIR", root / "data"))
    catalog = load_catalog(root)
    reg = ensure_loaded()
    missing = sorted(set(reg.methods) - set(catalog["methods"]))
    missing += sorted(set(reg.datasets) - set(catalog["datasets"]))
    if missing:
        raise CatalogError(f"No catalog entry for: {missing}. Add them to dictionary/catalog.yaml.")
    out = root / "docs" / "generated"
    (out / "methods").mkdir(parents=True, exist_ok=True)
    (out / "datasets").mkdir(parents=True, exist_ok=True)
    ladder = {int(k): v for k, v in catalog["ladder"].items()}

    frames: dict[str, Any] = {}
    if with_results:
        try:
            from recbench.results import load_runs

            # Untuned runs (default settings) and quick-tier tuned runs are labelled apart; dry runs of the tuning
            # pipeline on the smoke tier are left out, because their 2-setting searches mean little.
            frames = {"smoke": load_runs("smoke", tuning="defaults"), "full": load_runs("full", tuning="defaults"),
                      "quick (tuned)": load_runs("quick", tuning="tuned"), "full (tuned)": load_runs("full", tuning="tuned")}
        except Exception:  # noqa: BLE001 - docs still build without MLflow results
            frames = {}

    capability = []
    for name in sorted(reg.methods, key=lambda n: (catalog["methods"][n]["rung"], n)):
        spec, entry = reg.methods[name].spec, catalog["methods"][name]
        (out / "methods" / f"{name}.md").write_text(method_facts(name, entry, spec, ladder))
        (out / "methods" / f"{name}-results.md").write_text(method_results(name, frames, spec.impl_version))
        capability.append([
            f"[{entry['title']}]({name.replace('_', '-')}.md)", str(entry["rung"]), entry["family"],
            ", ".join(t for t in TASK_ORDER if Task(t) in spec.tasks), _yes(spec.uses_history), _yes(spec.sequence_aware),
            _yes(spec.scores_cold_items), _yes(spec.requires_side_features), entry["fidelity"], _yes(spec.ranked),
        ])
    quick = quick_methods(root)
    (out / "ladder.md").write_text(ladder_table(catalog, reg))
    (out / "glance.md").write_text(glance_table(catalog, reg, quick))
    update_readme(root, readme_block(catalog, reg, quick))
    (out / "capability.md").write_text(
        "<!-- generated -->\n\n"
        + _table(["Method", "Rung", "Family", "Tasks", "Uses history", "Order-aware", "New items", "Needs content", "Fidelity", "Ranked"],
                 capability)
    )
    metric_rows = []
    for name, cls in sorted(reg.metrics.items(), key=lambda kv: (kv[1].spec.kind, kv[0])):
        spec = cls.spec
        metric_rows.append([f"`{name}`", spec.kind, "↑ higher is better" if spec.higher_is_better else "↓ lower is better",
                            ", ".join(sorted(t.value for t in spec.tasks)), spec.description])
    (out / "metrics.md").write_text("<!-- generated -->\n\n" + _table(["Metric", "Kind", "Direction", "Tasks", "Meaning"], metric_rows))
    for name, cls in sorted(reg.datasets.items()):
        (out / "datasets" / f"{name}.md").write_text(dataset_facts(name, catalog["datasets"][name], cls.spec, data_dir))
    services = [[s["title"], s["status"], s["why_not_benchmarked"], f"[link]({s['url']})"] for s in catalog["services"].values()]
    (out / "services.md").write_text("<!-- generated -->\n\n" + _table(["Service", "Status (2026-10-02)", "Why not benchmarked live", "Docs"], services))
    return out


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate docs/generated/ from the catalog and results.")
    parser.add_argument("--no-results", action="store_true")
    args = parser.parse_args()
    print(build(with_results=not args.no_results))


if __name__ == "__main__":
    main()
